---
- name: Set the terraform deployment to {{ tf_task_state }}
  community.general.terraform:
    project_path: '{{ output_dir }}/terraform'
    check_destroy: '{{ true if tf_task_state == "present" else false }}'
    force_init: true
    state: '{{ tf_task_state|default("present") }}'
    backend_config_files:
    - '{{ output_dir }}/terraform/backend-config.hcl'
    variables:
      cluster_name: '{{ cluster_name }}'
      cluster_domain: '{{ cluster_domain }}'
      public_key: '{{ public_key }}'
      region: '{{ aws_region }}'
  environment: '{{ aws_env|from_yaml }}'
  vars:
    aws_env: |-
      {% for var, val in ansible_env.items() %}
      {% if var.startswith("AWS_") %}
      {{ var }}: {{ val }}
      {% endif %}
      {% endfor %}
  register: terraform
